### ISSUE TITLE
POD shows wrong parameters

### ISSUE THREAD

**Issue by maxhq** [nekokak/p5-DBIx-Handler#9]
The POD says:
`DBIx::Handler->new($dsn, $user, $pass, $opts);`
but it must be:
`DBIx::Handler->new($dsn, $user, $pass, $dbi_opts, $opts);`
Took me quite a while to figure out why it's not working ;-)

**Comment by karupanerura** [comment]
Oops, sorry. I'll fix it soon.

**Comment by karupanerura** [comment]
fixed it. thank you! and I'm sorry for the late.

**Comment by maxhq** [comment]
The issue didn't make it to the 3rd anniversary :laughing:
But I know how it is sometimes...

**Comment by karupanerura** [comment]
I success to remember this issue by TPCiP!
We easy develop amnesia when we are busy 🤒  (Just kidding. So really sorry for the late... and thank you a lot!)
